// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Data;

#nullable disable

namespace OnlineShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221219195826_specPonuda")]
    partial class specPonuda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShop.Modul1.Models.Boja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boja");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datum_kreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datum_modifikacije")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Kategorija");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.Kolekcija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Godina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("sezonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("sezonaId");

                    b.ToTable("Kolekcija");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.Odjel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Odjel");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.Podkategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KategorijaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datum_kreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datum_modifikacije")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Podkategorija");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.Popust", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Popust");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.Proizvod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<float>("Cijena")
                        .HasColumnType("real");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sifra")
                        .HasColumnType("int");

                    b.Property<int>("bojaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("datum_kreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datum_modifikacije")
                        .HasColumnType("datetime2");

                    b.Property<int?>("kategorijaId")
                        .HasColumnType("int");

                    b.Property<int?>("kolekcijaId")
                        .HasColumnType("int");

                    b.Property<int?>("odjelId")
                        .HasColumnType("int");

                    b.Property<int?>("podkategorijaId")
                        .HasColumnType("int");

                    b.Property<int?>("sezonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("bojaId");

                    b.HasIndex("kategorijaId");

                    b.HasIndex("kolekcijaId");

                    b.HasIndex("odjelId");

                    b.HasIndex("podkategorijaId");

                    b.HasIndex("sezonaId");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.Sezona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Doba")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Godina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sezona");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.SpecijalnaPonuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datum_pocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datum_zavrsetka")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SpecijalnaPonuda");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.SpecijalnaPonudaProizvod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("popustId")
                        .HasColumnType("int");

                    b.Property<int?>("proizvodId")
                        .HasColumnType("int");

                    b.Property<int?>("specijalnaPonudaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("popustId");

                    b.HasIndex("proizvodId");

                    b.HasIndex("specijalnaPonudaId");

                    b.ToTable("SpecijalnaPonudaProizvod");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.Kolekcija", b =>
                {
                    b.HasOne("OnlineShop.Modul1.Models.Sezona", "sezona")
                        .WithMany()
                        .HasForeignKey("sezonaId");

                    b.Navigation("sezona");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.Podkategorija", b =>
                {
                    b.HasOne("OnlineShop.Modul1.Models.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.Proizvod", b =>
                {
                    b.HasOne("OnlineShop.Modul1.Models.Boja", "boja")
                        .WithMany()
                        .HasForeignKey("bojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnlineShop.Modul1.Models.Kategorija", "kategorija")
                        .WithMany()
                        .HasForeignKey("kategorijaId");

                    b.HasOne("OnlineShop.Modul1.Models.Kolekcija", "kolekcija")
                        .WithMany()
                        .HasForeignKey("kolekcijaId");

                    b.HasOne("OnlineShop.Modul1.Models.Odjel", "odjel")
                        .WithMany()
                        .HasForeignKey("odjelId");

                    b.HasOne("OnlineShop.Modul1.Models.Podkategorija", "podkategorija")
                        .WithMany()
                        .HasForeignKey("podkategorijaId");

                    b.HasOne("OnlineShop.Modul1.Models.Sezona", "sezona")
                        .WithMany()
                        .HasForeignKey("sezonaId");

                    b.Navigation("boja");

                    b.Navigation("kategorija");

                    b.Navigation("kolekcija");

                    b.Navigation("odjel");

                    b.Navigation("podkategorija");

                    b.Navigation("sezona");
                });

            modelBuilder.Entity("OnlineShop.Modul1.Models.SpecijalnaPonudaProizvod", b =>
                {
                    b.HasOne("OnlineShop.Modul1.Models.Popust", "popust")
                        .WithMany()
                        .HasForeignKey("popustId");

                    b.HasOne("OnlineShop.Modul1.Models.Proizvod", "proizvod")
                        .WithMany()
                        .HasForeignKey("proizvodId");

                    b.HasOne("OnlineShop.Modul1.Models.SpecijalnaPonuda", "specijalnaPonuda")
                        .WithMany()
                        .HasForeignKey("specijalnaPonudaId");

                    b.Navigation("popust");

                    b.Navigation("proizvod");

                    b.Navigation("specijalnaPonuda");
                });
#pragma warning restore 612, 618
        }
    }
}
